apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins
  namespace: jenkins
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod

    # OAuth2 Proxy auth
    nginx.ingress.kubernetes.io/auth-url: "http://oauth2-proxy.jenkins.svc.cluster.local:4180/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://jenkins.kanchupati.com/oauth2/start?rd=$escaped_request_uri"
    nginx.ingress.kubernetes.io/auth-response-headers: "X-Auth-Request-User,X-Auth-Request-Email,X-Auth-Request-Groups"

    # Required for Jenkins uploads
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"

    # Force HTTPS
    nginx.ingress.kubernetes.io/ssl-redirect: "true"

spec:
  ingressClassName: nginx

  tls:
    - hosts:
        - jenkins.kanchupati.com
      secretName: jenkins-tls

  rules:
    - host: jenkins.kanchupati.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jenkins
                port:
                  number: 8080